// agency.ts generated by generate.sh
import { Entity } from "@core/app/base/entity"

export class Agency implements Entity {
  // Define your domain model here

  getData: () => object = () => {
    return {};
  };
}
