// passenger.ts generated by generate.sh
import { Entity } from "@core/app/base/entity"

export class Passenger implements Entity {
  // Define your domain model here

  getData: () => object = () => {
    return {};
  };
}
