export const flags = [
    {
        key: "Afghanistan",
        val: "https://cdn.countryflags.com/thumbs/afghanistan/flag-square-250.png",
    },
    { key: "Albania", val: "https://cdn.countryflags.com/thumbs/albania/flag-square-250.png" },
    { key: "Algeria", val: "https://cdn.countryflags.com/thumbs/algeria/flag-square-250.png" },
    { key: "Andorra", val: "https://cdn.countryflags.com/thumbs/andorra/flag-square-250.png" },
    { key: "Angola", val: "https://cdn.countryflags.com/thumbs/angola/flag-square-250.png" },
    {
        key: "Antigua and Barbuda",
        val: "https://cdn.countryflags.com/thumbs/antigua-and-barbuda/flag-square-250.png",
    },
    { key: "Argentina", val: "https://cdn.countryflags.com/thumbs/argentina/flag-square-250.png" },
    { key: "Armenia", val: "https://cdn.countryflags.com/thumbs/armenia/flag-square-250.png" },
    { key: "Australia", val: "https://cdn.countryflags.com/thumbs/australia/flag-square-250.png" },
    { key: "Austria", val: "https://cdn.countryflags.com/thumbs/austria/flag-square-250.png" },
    {
        key: "Azerbaijan",
        val: "https://cdn.countryflags.com/thumbs/azerbaijan/flag-square-250.png",
    },
    { key: "Bahamas", val: "https://cdn.countryflags.com/thumbs/bahamas/flag-square-250.png" },
    { key: "Bahrain", val: "https://cdn.countryflags.com/thumbs/bahrain/flag-square-250.png" },
    {
        key: "Bangladesh",
        val: "https://cdn.countryflags.com/thumbs/bangladesh/flag-square-250.png",
    },
    { key: "Barbados", val: "https://cdn.countryflags.com/thumbs/barbados/flag-square-250.png" },
    { key: "Belarus", val: "https://cdn.countryflags.com/thumbs/belarus/flag-square-250.png" },
    { key: "Belgium", val: "https://cdn.countryflags.com/thumbs/belgium/flag-square-250.png" },
    { key: "Belize", val: "https://cdn.countryflags.com/thumbs/belize/flag-square-250.png" },
    { key: "Benin", val: "https://cdn.countryflags.com/thumbs/benin/flag-square-250.png" },
    { key: "Bhutan", val: "https://cdn.countryflags.com/thumbs/bhutan/flag-square-250.png" },
    { key: "Bolivia", val: "https://cdn.countryflags.com/thumbs/bolivia/flag-square-250.png" },
    {
        key: "Bosnia and Herzegovina",
        val: "https://cdn.countryflags.com/thumbs/bosnia-and-herzegovina/flag-square-250.png",
    },
    { key: "Botswana", val: "https://cdn.countryflags.com/thumbs/botswana/flag-square-250.png" },
    { key: "Brazil", val: "https://cdn.countryflags.com/thumbs/brazil/flag-square-250.png" },
    { key: "Brunei", val: "https://cdn.countryflags.com/thumbs/brunei/flag-square-250.png" },
    { key: "Bulgaria", val: "https://cdn.countryflags.com/thumbs/bulgaria/flag-square-250.png" },
    {
        key: "Burkina Faso",
        val: "https://cdn.countryflags.com/thumbs/burkina-faso/flag-square-250.png",
    },
    { key: "Burundi", val: "https://cdn.countryflags.com/thumbs/burundi/flag-square-250.png" },
    {
        key: "Cabo Verde",
        val: "https://cdn.countryflags.com/thumbs/cape-verde/flag-square-250.png",
    },
    { key: "Cambodia", val: "https://cdn.countryflags.com/thumbs/cambodia/flag-square-250.png" },
    { key: "Cameroon", val: "https://cdn.countryflags.com/thumbs/cameroon/flag-square-250.png" },
    { key: "Canada", val: "https://cdn.countryflags.com/thumbs/canada/flag-square-250.png" },
    {
        key: "Central African Republic",
        val: "https://cdn.countryflags.com/thumbs/central-african-republic/flag-square-250.png",
    },
    { key: "Chad", val: "https://cdn.countryflags.com/thumbs/chad/flag-square-250.png" },
    { key: "Chile", val: "https://cdn.countryflags.com/thumbs/chile/flag-square-250.png" },
    { key: "China", val: "https://cdn.countryflags.com/thumbs/china/flag-square-250.png" },
    { key: "Colombia", val: "https://cdn.countryflags.com/thumbs/colombia/flag-square-250.png" },
    { key: "Comoros", val: "https://cdn.countryflags.com/thumbs/comoros/flag-square-250.png" },
    {
        key: "Congo (Democratic Republic)",
        val: "https://cdn.countryflags.com/thumbs/congo-democratic-republic-of-the/flag-square-250.png",
    },
    {
        key: "Congo (Republic)",
        val: "https://cdn.countryflags.com/thumbs/congo-republic-of-the/flag-square-250.png",
    },
    {
        key: "Costa Rica",
        val: "https://cdn.countryflags.com/thumbs/costa-rica/flag-square-250.png",
    },
    { key: "Croatia", val: "https://cdn.countryflags.com/thumbs/croatia/flag-square-250.png" },
    { key: "Cuba", val: "https://cdn.countryflags.com/thumbs/cuba/flag-square-250.png" },
    { key: "Cyprus", val: "https://cdn.countryflags.com/thumbs/cyprus/flag-square-250.png" },
    {
        key: "Czech Republic",
        val: "https://cdn.countryflags.com/thumbs/czech-republic/flag-square-250.png",
    },
    { key: "Denmark", val: "https://cdn.countryflags.com/thumbs/denmark/flag-square-250.png" },
    { key: "Djibouti", val: "https://cdn.countryflags.com/thumbs/djibouti/flag-square-250.png" },
    { key: "Dominica", val: "https://cdn.countryflags.com/thumbs/dominica/flag-square-250.png" },
    {
        key: "Dominican Republic",
        val: "https://cdn.countryflags.com/thumbs/dominican-republic/flag-square-250.png",
    },
    { key: "Ecuador", val: "https://cdn.countryflags.com/thumbs/ecuador/flag-square-250.png" },
    { key: "Egypt", val: "https://cdn.countryflags.com/thumbs/egypt/flag-square-250.png" },
    {
        key: "El Salvador",
        val: "https://cdn.countryflags.com/thumbs/el-salvador/flag-square-250.png",
    },
    {
        key: "Equatorial Guinea",
        val: "https://cdn.countryflags.com/thumbs/equatorial-guinea/flag-square-250.png",
    },
    { key: "Eritrea", val: "https://cdn.countryflags.com/thumbs/eritrea/flag-square-250.png" },
    { key: "Estonia", val: "https://cdn.countryflags.com/thumbs/estonia/flag-square-250.png" },
    { key: "Eswatini", val: "https://cdn.countryflags.com/thumbs/swaziland/flag-square-250.png" },
    { key: "Ethiopia", val: "https://cdn.countryflags.com/thumbs/ethiopia/flag-square-250.png" },
    { key: "Fiji", val: "https://cdn.countryflags.com/thumbs/fiji/flag-square-250.png" },
    { key: "Finland", val: "https://cdn.countryflags.com/thumbs/finland/flag-square-250.png" },
    { key: "France", val: "https://cdn.countryflags.com/thumbs/france/flag-square-250.png" },
    { key: "Gabon", val: "https://cdn.countryflags.com/thumbs/gabon/flag-square-250.png" },
    { key: "Gambia", val: "https://cdn.countryflags.com/thumbs/gambia/flag-square-250.png" },
    { key: "Georgia", val: "https://cdn.countryflags.com/thumbs/georgia/flag-square-250.png" },
    { key: "Germany", val: "https://cdn.countryflags.com/thumbs/germany/flag-square-250.png" },
    { key: "Ghana", val: "https://cdn.countryflags.com/thumbs/ghana/flag-square-250.png" },
    { key: "Greece", val: "https://cdn.countryflags.com/thumbs/greece/flag-square-250.png" },
    { key: "Grenada", val: "https://cdn.countryflags.com/thumbs/grenada/flag-square-250.png" },
    { key: "Guatemala", val: "https://cdn.countryflags.com/thumbs/guatemala/flag-square-250.png" },
    { key: "Guinea", val: "https://cdn.countryflags.com/thumbs/guinea/flag-square-250.png" },
    {
        key: "Guinea-Bissau",
        val: "https://cdn.countryflags.com/thumbs/guinea-bissau/flag-square-250.png",
    },
    { key: "Guyana", val: "https://cdn.countryflags.com/thumbs/guyana/flag-square-250.png" },
    { key: "Haiti", val: "https://cdn.countryflags.com/thumbs/haiti/flag-square-250.png" },
    { key: "Honduras", val: "https://cdn.countryflags.com/thumbs/honduras/flag-square-250.png" },
    { key: "Hungary", val: "https://cdn.countryflags.com/thumbs/hungary/flag-square-250.png" },
    { key: "Iceland", val: "https://cdn.countryflags.com/thumbs/iceland/flag-square-250.png" },
    { key: "India", val: "https://cdn.countryflags.com/thumbs/india/flag-square-250.png" },
    { key: "Indonesia", val: "https://cdn.countryflags.com/thumbs/indonesia/flag-square-250.png" },
    { key: "Iran", val: "https://cdn.countryflags.com/thumbs/iran/flag-square-250.png" },
    { key: "Iraq", val: "https://cdn.countryflags.com/thumbs/iraq/flag-square-250.png" },
    { key: "Ireland", val: "https://cdn.countryflags.com/thumbs/ireland/flag-square-250.png" },
    { key: "Israel", val: "https://cdn.countryflags.com/thumbs/israel/flag-square-250.png" },
    { key: "Italy", val: "https://cdn.countryflags.com/thumbs/italy/flag-square-250.png" },
    { key: "Jamaica", val: "https://cdn.countryflags.com/thumbs/jamaica/flag-square-250.png" },
    { key: "Japan", val: "https://cdn.countryflags.com/thumbs/japan/flag-square-250.png" },
    { key: "Jordan", val: "https://cdn.countryflags.com/thumbs/jordan/flag-square-250.png" },
    {
        key: "Kazakhstan",
        val: "https://cdn.countryflags.com/thumbs/kazakhstan/flag-square-250.png",
    },
    { key: "Kenya", val: "https://cdn.countryflags.com/thumbs/kenya/flag-square-250.png" },
    { key: "Kiribati", val: "https://cdn.countryflags.com/thumbs/kiribati/flag-square-250.png" },
    { key: "Kuwait", val: "https://cdn.countryflags.com/thumbs/kuwait/flag-square-250.png" },
    {
        key: "Kyrgyzstan",
        val: "https://cdn.countryflags.com/thumbs/kyrgyzstan/flag-square-250.png",
    },
    { key: "Laos", val: "https://cdn.countryflags.com/thumbs/laos/flag-square-250.png" },
    { key: "Latvia", val: "https://cdn.countryflags.com/thumbs/latvia/flag-square-250.png" },
    { key: "Lebanon", val: "https://cdn.countryflags.com/thumbs/lebanon/flag-square-250.png" },
    { key: "Lesotho", val: "https://cdn.countryflags.com/thumbs/lesotho/flag-square-250.png" },
    { key: "Liberia", val: "https://cdn.countryflags.com/thumbs/liberia/flag-square-250.png" },
    { key: "Libya", val: "https://cdn.countryflags.com/thumbs/libya/flag-square-250.png" },
    {
        key: "Liechtenstein",
        val: "https://cdn.countryflags.com/thumbs/liechtenstein/flag-square-250.png",
    },
    { key: "Lithuania", val: "https://cdn.countryflags.com/thumbs/lithuania/flag-square-250.png" },
    {
        key: "Luxembourg",
        val: "https://cdn.countryflags.com/thumbs/luxembourg/flag-square-250.png",
    },
    {
        key: "Madagascar",
        val: "https://cdn.countryflags.com/thumbs/madagascar/flag-square-250.png",
    },
    { key: "Malawi", val: "https://cdn.countryflags.com/thumbs/malawi/flag-square-250.png" },
    { key: "Malaysia", val: "https://cdn.countryflags.com/thumbs/malaysia/flag-square-250.png" },
    { key: "Maldives", val: "https://cdn.countryflags.com/thumbs/maldives/flag-square-250.png" },
    { key: "Mali", val: "https://cdn.countryflags.com/thumbs/mali/flag-square-250.png" },
    { key: "Malta", val: "https://cdn.countryflags.com/thumbs/malta/flag-square-250.png" },
    {
        key: "Marshall Islands",
        val: "https://cdn.countryflags.com/thums/marshall-islands/flag-square-250.png",
    },
    {
        key: "Mauritania",
        val: "https://cdn.countryflags.com/thumbs/mauritania/flag-square-250.png",
    },
    { key: "Mauritius", val: "https://cdn.countryflags.com/thumbs/mauritius/flag-square-250.png" },
    { key: "Mexico", val: "https://cdn.countryflags.com/thumbs/mexico/flag-square-250.png" },
    {
        key: "Micronesia",
        val: "https://cdn.countryflags.com/thumbs/micronesia/flag-square-250.png",
    },
    { key: "Moldova", val: "https://cdn.countryflags.com/thumbs/moldova/flag-square-250.png" },
    { key: "Monaco", val: "https://cdn.countryflags.com/thumbs/monaco/flag-square-250.png" },
    { key: "Mongolia", val: "https://cdn.countryflags.com/thumbs/mongolia/flag-square-250.png" },
    {
        key: "Montenegro",
        val: "https://cdn.countryflags.com/thumbs/montenegro/flag-square-250.png",
    },
    { key: "Morocco", val: "https://cdn.countryflags.com/thumbs/morocco/flag-square-250.png" },
    {
        key: "Mozambique",
        val: "https://cdn.countryflags.com/thumbs/mozambique/flag-square-250.png",
    },
    { key: "Myanmar", val: "https://cdn.countryflags.com/thumbs/myanmar/flag-square-250.png" },
    { key: "Namibia", val: "https://cdn.countryflags.com/thumbs/namibia/flag-square-250.png" },
    { key: "Nauru", val: "https://cdn.countryflags.com/thumbs/nauru/flag-square-250.png" },
    { key: "Nepal", val: "https://cdn.countryflags.com/thumbs/nepal/flag-square-250.png" },
    {
        key: "Netherlands",
        val: "https://cdn.countryflags.com/thumbs/netherlands/flag-square-250.png",
    },
    {
        key: "New Zealand",
        val: "https://cdn.countryflags.com/thumbs/new-zealand/flag-square-250.png",
    },
    { key: "Nicaragua", val: "https://cdn.countryflags.com/thumbs/nicaragua/flag-square-250.png" },
    { key: "Niger", val: "https://cdn.countryflags.com/thumbs/niger/flag-square-250.png" },
    { key: "Nigeria", val: "https://cdn.countryflags.com/thumbs/nigeria/flag-square-250.png" },
    {
        key: "North Korea",
        val: "https://cdn.countryflags.com/thumbs/north-korea/flag-square-250.png",
    },
    {
        key: "North Macedonia",
        val: "https://cdn.countryflags.com/thumbs/north-macedonia/flag-square-250.png",
    },
    { key: "Norway", val: "https://cdn.countryflags.com/thumbs/norway/flag-square-250.png" },
    { key: "Oman", val: "https://cdn.countryflags.com/thumbs/oman/flag-square-250.png" },
    { key: "Pakistan", val: "https://cdn.countryflags.com/thumbs/pakistan/flag-square-250.png" },
    { key: "Palau", val: "https://cdn.countryflags.com/thumbs/palau/flag-square-250.png" },
    { key: "Palestine", val: "https://cdn.countryflags.com/thumbs/palestine/flag-square-250.png" },
    { key: "Panama", val: "https://cdn.countryflags.com/thumbs/panama/flag-square-250.png" },
    {
        key: "Papua New Guinea",
        val: "https://cdn.countryflags.com/thumbs/papua-new-guinea/flag-square-250.png",
    },
    { key: "Paraguay", val: "https://cdn.countryflags.com/thumbs/paraguay/flag-square-250.png" },
    { key: "Peru", val: "https://cdn.countryflags.com/thumbs/peru/flag-square-250.png" },
    {
        key: "Philippines",
        val: "https://cdn.countryflags.com/thumbs/philippines/flag-square-250.png",
    },
    { key: "Poland", val: "https://cdn.countryflags.com/thumbs/poland/flag-square-250.png" },
    { key: "Portugal", val: "https://cdn.countryflags.com/thumbs/portugal/flag-square-250.png" },
    { key: "Qatar", val: "https://cdn.countryflags.com/thumbs/qatar/flag-square-250.png" },
    { key: "Romania", val: "https://cdn.countryflags.com/thumbs/romania/flag-square-250.png" },
    { key: "Russia", val: "https://cdn.countryflags.com/thumbs/russia/flag-square-250.png" },
    { key: "Rwanda", val: "https://cdn.countryflags.com/thumbs/rwanda/flag-square-250.png" },
    {
        key: "Saint Kitts and Nevis",
        val: "https://cdn.countryflags.com/thumbs/saint-kitts-and-nevis/flag-square-250.png",
    },
    {
        key: "Saint Lucia",
        val: "https://cdn.countryflags.com/thumbs/saint-lucia/flag-square-250.png",
    },
    {
        key: "Saint Vincent and the Grenadines",
        val: "https://cdn.countryflags.com/thumbs/saint-vincent-and-the-grenadines/flag-square-250.png",
    },
    { key: "Samoa", val: "https://cdn.countryflags.com/thumbs/samoa/flag-square-250.png" },
    {
        key: "San Marino",
        val: "https://cdn.countryflags.com/thumbs/san-marino/flag-square-250.png",
    },
    {
        key: "Sao Tome and Principe",
        val: "https://cdn.countryflags.com/thumbs/sao-tome-and-principe/flag-square-250.png",
    },
    {
        key: "Saudi Arabia",
        val: "https://cdn.countryflags.com/thumbs/saudi-arabia/flag-square-250.png",
    },
    { key: "Senegal", val: "https://cdn.countryflags.com/thumbs/senegal/flag-square-250.png" },
    { key: "Serbia", val: "https://cdn.countryflags.com/thumbs/serbia/flag-square-250.png" },
    {
        key: "Seychelles",
        val: "https://cdn.countryflags.com/thumbs/seychelles/flag-square-250.png",
    },
    {
        key: "Sierra Leone",
        val: "https://cdn.countryflags.com/thumbs/sierra-leone/flag-square-250.png",
    },
    { key: "Singapore", val: "https://cdn.countryflags.com/thumbs/singapore/flag-square-250.png" },
    { key: "Slovakia", val: "https://cdn.countryflags.com/thumbs/slovakia/flag-square-250.png" },
    { key: "Slovenia", val: "https://cdn.countryflags.com/thumbs/slovenia/flag-square-250.png" },
    {
        key: "Solomon Islands",
        val: "https://cdn.countryflags.com/thumbs/solomon-islands/flag-square-250.png",
    },
    { key: "Somalia", val: "https://cdn.countryflags.com/thumbs/somalia/flag-square-250.png" },
    {
        key: "South Africa",
        val: "https://cdn.countryflags.com/thumbs/south-africa/flag-square-250.png",
    },
    {
        key: "South Korea",
        val: "https://cdn.countryflags.com/thumbs/south-korea/flag-square-250.png",
    },
    {
        key: "South Sudan",
        val: "https://cdn.countryflags.com/thumbs/south-sudan/flag-square-250.png",
    },
    { key: "Spain", val: "https://cdn.countryflags.com/thumbs/spain/flag-square-250.png" },
    { key: "Sri Lanka", val: "https://cdn.countryflags.com/thumbs/sri-lanka/flag-square-250.png" },
    { key: "Sudan", val: "https://cdn.countryflags.com/thumbs/sudan/flag-square-250.png" },
    { key: "Suriname", val: "https://cdn.countryflags.com/thumbs/suriname/flag-square-250.png" },
    { key: "Sweden", val: "https://cdn.countryflags.com/thumbs/sweden/flag-square-250.png" },
    {
        key: "Switzerland",
        val: "https://cdn.countryflags.com/thumbs/switzerland/flag-square-250.png",
    },
    { key: "Syria", val: "https://cdn.countryflags.com/thumbs/syria/flag-square-250.png" },
    { key: "Taiwan", val: "https://cdn.countryflags.com/thumbs/taiwan/flag-square-250.png" },
    {
        key: "Tajikistan",
        val: "https://cdn.countryflags.com/thumbs/tajikistan/flag-square-250.png",
    },
    { key: "Tanzania", val: "https://cdn.countryflags.com/thumbs/tanzania/flag-square-250.png" },
    { key: "Thailand", val: "https://cdn.countryflags.com/thumbs/thailand/flag-square-250.png" },
    {
        key: "Timor-Leste",
        val: "https://cdn.countryflags.com/thumbs/east-timor/flag-square-250.png",
    },
    { key: "Togo", val: "https://cdn.countryflags.com/thumbs/togo/flag-square-250.png" },
    { key: "Tonga", val: "https://cdn.countryflags.com/thumbs/tonga/flag-square-250.png" },
    {
        key: "Trinidad and Tobago",
        val: "https://cdn.countryflags.com/thumbs/trinidad-and-tobago/flag-square-250.png",
    },
    { key: "Tunisia", val: "https://cdn.countryflags.com/thumbs/tunisia/flag-square-250.png" },
    { key: "Turkey", val: "https://cdn.countryflags.com/thumbs/turkey/flag-square-250.png" },
    {
        key: "Turkmenistan",
        val: "https://cdn.countryflags.com/thumbs/turkmenistan/flag-square-250.png",
    },
    { key: "Tuvalu", val: "https://cdn.countryflags.com/thumbs/tuvalu/flag-square-250.png" },
    { key: "Uganda", val: "https://cdn.countryflags.com/thumbs/uganda/flag-square-250.png" },
    { key: "Ukraine", val: "https://cdn.countryflags.com/thumbs/ukraine/flag-square-250.png" },
    {
        key: "United Arab Emirates",
        val: "https://cdn.countryflags.com/thumbs/united-arab-emirates/flag-square-250.png",
    },
    {
        key: "United Kingdom",
        val: "https://cdn.countryflags.com/thumbs/united-kingdom/flag-square-250.png",
    },
    {
        key: "United States",
        val: "https://cdn.countryflags.com/thumbs/united-states-of-america/flag-square-250.png",
    },
    { key: "Uruguay", val: "https://cdn.countryflags.com/thumbs/uruguay/flag-square-250.png" },
    {
        key: "Uzbekistan",
        val: "https://cdn.countryflags.com/thumbs/uzbekistan/flag-square-250.png",
    },
    { key: "Vanuatu", val: "https://cdn.countryflags.com/thumbs/vanuatu/flag-square-250.png" },
    {
        key: "Vatican City",
        val: "https://cdn.countryflags.com/thumbs/vatican-city/flag-square-250.png",
    },
    { key: "Venezuela", val: "https://cdn.countryflags.com/thumbs/venezuela/flag-square-250.png" },
    { key: "Vietnam", val: "https://cdn.countryflags.com/thumbs/vietnam/flag-square-250.png" },
    { key: "Yemen", val: "https://cdn.countryflags.com/thumbs/yemen/flag-square-250.png" },
    { key: "Zambia", val: "https://cdn.countryflags.com/thumbs/zambia/flag-square-250.png" },
    { key: "Zimbabwe", val: "https://cdn.countryflags.com/thumbs/zimbabwe/flag-square-250.png" },
];
