// passenger.service.ts generated by generate.sh
import { visaBookingRepo } from "@/core/infrastructure/repositories/visa-booking.repo";
import { validateInput } from "@/utils/validate-input";
import { passengerRepo } from "@core/infrastructure/repositories/passenger.repo";
import { Prisma } from "@prisma/client";
import Joi from "joi";
import { ConstraintError } from "../base/constraint-error";

export const PassengerService = {
    updatePassenger: async ({
        id,
        ...inputData
    }: { id: string } & Prisma.PassengerUpdateInput & {
            deletedDocs: any;
            files: Express.Multer.File[];
        }) => {
        const existingPassenger = await passengerRepo.exists(id);
        if (!existingPassenger) {
            console.error(`Passenger not found`);
            throw new ConstraintError(
                "Passenger not found",
                404,
                "RESOURCE_NOT_FOUND",
                `Passenger could not be found`
            );
        }

        const { deletedDocs, files } = inputData;

        let parsedDeletedDocs: string[] = [];
        if (deletedDocs) {
            try {
                parsedDeletedDocs = Array.isArray(deletedDocs)
                    ? (deletedDocs as string[])
                    : JSON.parse(deletedDocs as string);
            } catch (parseErr) {
                console.error("Invalid deletedDocs format:", deletedDocs);
                throw new ConstraintError(
                    "Invalid deletedDocs format",
                    400,
                    "INVALID_INPUT",
                    "deletedDocs must be a valid JSON array of document IDs"
                );
            }
        }

        if (files.length === 0 && parsedDeletedDocs.length === 0) {
            console.error("No files to add or delete provided for update");
            throw new ConstraintError(
                "Nothing to update",
                400,
                "MISSING_DOCUMENTS",
                "You must provide at least one new file (documents) or a deletedDocs array"
            );
        }

        const dateFields = ["dateOfBirth", "passportDeliveryDate", "passportExpirationDate"];
        for (const field of dateFields) {
            if (inputData[field]) {
                inputData[field] = new Date(inputData[field] as string);
            }
        }

        const updatedPassenger = await passengerRepo.update(id, {
            ...inputData,
            files,
            deletedDocs: parsedDeletedDocs,
        });

        return updatedPassenger;
    },

    createPassenger: async ({
        files,
        ...rest
    }: Omit<Prisma.PassengerCreateInput, "visaRequest" | "passengerDocuments"> & {
        files: Express.Multer.File[];
        visaRequestId: string;
    }) => {
        console.debug("[PassengerService] createPassenger called", { filesCount: files?.length, ...rest });

        // Joi schema without docs
        const createPassengerSchema = Joi.object({
            visaRequestId: Joi.string().guid({ version: "uuidv4" }).required().messages({
                "any.required": "Visa request ID is required",
                "string.guid": "Visa request ID must be a valid UUID",
            }),

            name: Joi.string().required().messages({
                "any.required": "Passenger name is required",
            }),

            surname: Joi.string().required().messages({
                "any.required": "Passenger surname is required",
            }),

            placeOfBirth: Joi.string().required().messages({
                "any.required": "Place of birth is required",
            }),

            dateOfBirth: Joi.date().iso().required().messages({
                "any.required": "Date of birth is required",
                "date.format": "Date of birth must be a valid ISO date string",
            }),

            passportNumber: Joi.string().required().messages({
                "any.required": "Passport number is required",
            }),

            passportDeliveryDate: Joi.date().iso().required().messages({
                "any.required": "Passport delivery date is required",
                "date.format": "Passport delivery date must be a valid ISO date string",
            }),

            passportExpirationDate: Joi.date().iso().required().messages({
                "any.required": "Passport expiration date is required",
                "date.format": "Passport expiration date must be a valid ISO date string",
            }),

            email: Joi.string().email().required().messages({
                "any.required": "Email is required",
                "string.email": "Email must be a valid email address",
            }),

            phone: Joi.string().required().messages({
                "any.required": "Phone number is required",
            }),
        });

        // Validate the rest of the data (excluding files)
        let visaRequestId, validatedData;
        try {
            ({ visaRequestId, ...validatedData } = validateInput(createPassengerSchema, rest));
            console.debug("[PassengerService] Input validated", { visaRequestId, validatedData });
        } catch (err) {
            console.error("[PassengerService] Input validation failed", err);
            throw err;
        }

        // Ensure at least one file is uploaded
        if (!files || files.length === 0) {
            console.error("[PassengerService] No files uploadded");
            throw new ConstraintError(
                "At least one file is required",
                400,
                "MISSING_FILES",
                "You must upload at least one document"
            );
        }

        // Check visa request exists
        console.debug("[PassengerService] Checking visa request existence", { visaRequestId });
        const visaRequestExists = await visaBookingRepo.exists({ id: visaRequestId });

        if (!visaRequestExists) {
            console.error("[PassengerService] Visa Request not found", { visaRequestId });
            throw new ConstraintError(
                "Visa Request not found",
                404,
                "RESOURCE_NOT_FOUND",
                `Visa Request could not be found`
            );
        }

        // Call repository
        console.debug("[PassengerService] Creating passenger", { visaRequestId, validatedData, filesCount: files.length });
        const data = await passengerRepo.create({
            visaRequestId,
            files,
            ...validatedData,
        });

        console.debug("[PassengerService] Passenger created", { passengerId: data?.id });
        return data;
    },

    deletePassenger: async (id: string) => {
        const passengerExists = await passengerRepo.exists(id);

        if (!passengerExists) {
            throw new ConstraintError(
                "Passenger not found",
                404,
                "RESOURCE_NOT_FOUND",
                `Passenger with ID ${id} not found`
            );
        }

        await passengerRepo.delete(id);
    },
};
