// passenger.service.ts generated by generate.sh
import { visaBookingRepo } from "@/core/infrastructure/repositories/visa-booking.repo";
import { validateInput } from "@/utils/validate-input";
import { passengerRepo } from "@core/infrastructure/repositories/passenger.repo";
import { Prisma } from "@prisma/client";
import Joi from "joi";
import { ConstraintError } from "../base/constraint-error";

export const PassengerService = {
    createPassenger: async ({
        files,
        ...rest
    }: Prisma.PassengerCreateInput & {
        files: Express.Multer.File[];
        visaRequestId: string;
    }) => {
        const createPassengerSchema = Joi.object({
            visaRequestId: Joi.string().guid({ version: "uuidv4" }).required().messages({
                "any.required": "Visa request ID is required",
                "string.guid": "Visa request ID must be a valid UUID",
            }),

            name: Joi.string().required().messages({
                "any.required": "Passenger name is required",
            }),

            surname: Joi.string().required().messages({
                "any.required": "Passenger surname is required",
            }),

            placeOfBirth: Joi.string().required().messages({
                "any.required": "Place of birth is required",
            }),

            dateOfBirth: Joi.date().iso().required().messages({
                "any.required": "Date of birth is required",
                "date.format": "Date of birth must be a valid ISO date string",
            }),

            passportNumber: Joi.string().required().messages({
                "any.required": "Passport number is required",
            }),

            passportDeliveryDate: Joi.date().iso().required().messages({
                "any.required": "Passport delivery date is required",
                "date.format": "Passport delivery date must be a valid ISO date string",
            }),

            passportExpirationDate: Joi.date().iso().required().messages({
                "any.required": "Passport expiration date is required",
                "date.format": "Passport expiration date must be a valid ISO date string",
            }),

            email: Joi.string().email().required().messages({
                "any.required": "Email is required",
                "string.email": "Email must be a valid email address",
            }),

            phone: Joi.string().required().messages({
                "any.required": "Phone number is required",
            }),

            docs: Joi.array().items(Joi.string()).min(1).required().messages({
                "any.required": "At least one document is required",
                "array.base": "Docs must be an array of strings",
                "array.min": "At least one document is required",
            }),
        });

        const { visaRequestId, ...rawData } = validateInput(createPassengerSchema, {
            ...rest,
            docs: files.map((file) => file.path),
        });

        const visaRequestExists = await visaBookingRepo.exists({ id: visaRequestId });

        if (!visaRequestExists) {
            throw new ConstraintError(
                "Visa Request not found",
                404,
                "RESOURCE_NOT_FOUND",
                `Visa Request could not found`
            );
        }

        const data = await passengerRepo.create({
            visaRequestId,
            files,
            ...rawData,
        });

        return data;
    },

    deletePassenger: async (id: string) => {
        const passengerExists = await passengerRepo.exists(id);

        if (!passengerExists) {
            throw new ConstraintError(
                "Passenger not found",
                404,
                "RESOURCE_NOT_FOUND",
                `Passenger with ID ${id} not found`
            );
        }

        await passengerRepo.delete(id);
    },
};
