// permission.service.ts generated by generate.sh
import { permissionRepo } from "@core/infrastructure/repositories/permission.repo"

export const PermissionService = {
  // Your service logic here
}

