// role.service.ts generated by generate.sh
import { prisma } from "@/config";
import { roleRepo } from "@core/infrastructure/repositories/role.repo";

export const RoleService = {
    getAllRoles: async () => {
        return prisma.role.findMany({
            where: {
                name: {
                    not: "super_admin",
                },
            },
        });
    },
};
