// visa.service.ts generated by generate.sh
import { visaRepo } from "@core/infrastructure/repositories/visa.repo";
import { Prisma } from "@prisma/client";
import { ConstraintError } from "../base/constraint-error";
import { validate as isValidUuid } from "uuid";
import { countryRepo } from "@/core/infrastructure/repositories/country.repo";
import Joi from "joi";
import { validateInput } from "@/utils/validate-input";

export const VisaService = {
    createNewVisa: async (inputData: Prisma.VisaCreateInput & { countryId: string }) => {
        const createVisaSchema = Joi.object({
            countryId: Joi.string().guid({ version: "uuidv4" }).required().messages({
                "string.guid": "Country ID must be a valid UUID",
                "any.required": "Country ID is required",
            }),
            name: Joi.string().required(),
            price: Joi.number().required(),
            currency: Joi.string().required(),
            description: Joi.string().required(),
            conditions: Joi.string().required(),
            duration: Joi.string().required(),
            status: Joi.boolean().required(),
        });

        const { countryId, ...rest } = validateInput<typeof inputData>(createVisaSchema, inputData);

        const countryExists = await countryRepo.countryExist({ id: countryId });

        if (!countryExists) {
            throw new ConstraintError(
                "Country not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Country could not be found`
            );
        }

        const createInput: Prisma.VisaCreateInput = {
            ...rest,
            country: {
                connect: { id: countryId },
            },
        };

        const data = await visaRepo.create(createInput);
        return data;
    },

    getVisaById: async ({ id }: { id: string }) => {
        const data = await visaRepo.findOne({ id });

        if (!data) {
            throw new ConstraintError(
                "Visa not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This VISA could not be found`
            );
        }

        return data;
    },

    deleteVisa: async ({ id }: { id: string }) => {
        const isExist = await visaRepo.exists({ id });

        if (!isExist) {
            throw new ConstraintError(
                "Visa not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Visa could not be found`
            );
        }

        await visaRepo.delete({ id });
    },
    getAllVisa: async ({
        page,
        pageSize,
        countryId,
    }: {
        page: number;
        pageSize: number;
        countryId: string | undefined;
    }) => {
        const data = await visaRepo.findAll({
            page: Number(page),
            pageSize: Number(pageSize),
            countryId: typeof countryId === "string" ? countryId : undefined,
        });

        return data;
    },

    updateVisa: async (
        inputData: Prisma.VisaUpdateInput & {
            countryId?: string;
        }
    ) => {
        const updateVisaSchema = Joi.object({
            name: Joi.string().optional(),
            price: Joi.number().optional(),
            currency: Joi.string().optional(),
            description: Joi.string().optional(),
            conditions: Joi.string().optional(),
            duration: Joi.string().optional(),
            status: Joi.boolean().optional(),
            countryId: Joi.string().guid({ version: "uuidv4" }).optional().messages({
                "string.guid": "Country ID must be a valid UUID",
            }),
        });

        const { id, ...updateFields } = inputData;

        if (!id || typeof id !== "string" || id.trim() === "" || !isValidUuid(id)) {
            throw new ConstraintError(
                "Invalid ID format",
                400,
                "VALIDATION_ERROR",
                "Visa ID must be a valid UUID"
            );
        }

        // Ensure there is at least one field to update
        if (
            typeof updateFields !== "object" ||
            updateFields === null ||
            Object.keys(updateFields).length === 0
        ) {
            throw new ConstraintError(
                "Invalid request body",
                400,
                "INVALID_REQUEST_BODY",
                "Request body must be a non-empty object with update fields"
            );
        }

        // Validate fields using Joi
        const validated = validateInput<typeof updateFields>(updateVisaSchema, updateFields);
        const { countryId, ...rest } = validated;

        const isExist = await visaRepo.exists({ id });
        if (!isExist) {
            throw new ConstraintError(
                "Visa not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Visa does not exist`
            );
        }

        if (countryId) {
            const countryExists = await countryRepo.countryExist({ id: countryId });
            if (!countryExists) {
                throw new ConstraintError(
                    "Country not found",
                    404,
                    "RESOURCE_NOT_FOUND",
                    `This Country could not be found`
                );
            }
        }

        const data = await visaRepo.updateVisa(id, {
            ...rest,
            ...(countryId && {
                country: {
                    connect: {
                        id: countryId,
                    },
                },
            }),
        });

        return data;
    },
};
