// visa.service.ts generated by generate.sh
import { visaRepo } from "@core/infrastructure/repositories/visa.repo";
import { Prisma } from "@prisma/client";
import { ConstraintError } from "../base/constraint-error";
import { validate as isValidUuid } from "uuid";
import { countryRepo } from "@/core/infrastructure/repositories/country.repo";

export const VisaService = {
    createNewVisa: async (inputData: Prisma.VisaCreateInput & { countryId: string }) => {
        const { countryId, ...rest } = inputData;

        if (
            !countryId ||
            typeof countryId !== "string" ||
            countryId.trim() === "" ||
            !isValidUuid(countryId)
        ) {
            throw new ConstraintError(
                "Country ID validation failed",
                400,
                "INVALID_INPUT",
                "Country ID must be provided as a non-empty string"
            );
        }

        const countryExists = await countryRepo.countryExist({ id: countryId });

        if (!countryExists) {
            throw new ConstraintError(
                "Country not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Country could not be found`
            );
        }

        const requiredFields = [
            "name",
            "price",
            "currency",
            "description",
            "conditions",
            "duration",
            "status",
        ];

        for (const field of requiredFields) {
            if (rest[field] === undefined) {
                throw new ConstraintError(
                    "Missing required field",
                    400,
                    "MISSING_REQUIRED_FIELD",
                    `${field} is a required field`
                );
            }
        }

        const createInput: Prisma.VisaCreateInput = {
            ...rest,
            country: {
                connect: { id: countryId },
            },
        };

        const data = await visaRepo.create(createInput);
        return data;
    },

    getVisaById: async ({ id }: { id: string | undefined }) => {
        if (!id || typeof id !== "string" || id.trim() === "" || !isValidUuid(id)) {
            throw new ConstraintError(
                "Invalid ID format",
                400,
                "VALIDATION_ERROR",
                "Visa ID must be a valid UUID"
            );
        }

        const data = await visaRepo.findOne({ id });

        if (!data) {
            throw new ConstraintError(
                "Visa not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This VISA could not be found`
            );
        }

        return data;
    },

    deleteVisa: async ({ id }: { id: string | undefined }) => {
        if (!id || typeof id !== "string" || id.trim() === "" || !isValidUuid(id)) {
            throw new ConstraintError(
                "Invalid ID format",
                400,
                "VALIDATION_ERROR",
                "Visa ID must be a valid UUID"
            );
        }

        const isExist = await visaRepo.exists({ id });

        if (!isExist) {
            throw new ConstraintError(
                "Country not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Country could not be found`
            );
        }

        await visaRepo.delete({ id });
    },
    getAllVisa: async ({
        page,
        pageSize,
        countryId,
    }: {
        page: number;
        pageSize: number;
        countryId: string | undefined;
    }) => {
        const data = await visaRepo.findAll({
            page: Number(page),
            pageSize: Number(pageSize),
            countryId: typeof countryId === "string" ? countryId : undefined,
        });

        return data;
    },

    updateVisa: async (
        inputData: Prisma.VisaUpdateInput & {
            countryId?: string;
        }
    ) => {
        const { id, countryId, ...rest } = inputData;

        if (!id || typeof id !== "string" || id.trim() === "" || !isValidUuid(id)) {
            throw new ConstraintError(
                "Invalid ID format",
                400,
                "VALIDATION_ERROR",
                "Visa ID must be a valid UUID"
            );
        }

        if (
            typeof inputData !== "object" ||
            inputData === null ||
            Object.keys(inputData).length === 0
        ) {
            throw new ConstraintError(
                "Invalid request body",
                400,
                "INVALID_REQUEST_BODY",
                "Request body must be a non-empty object with update fields"
            );
        }

        const allowedFields = [
            "name",
            "price",
            "currency",
            "description",
            "conditions",
            "duration",
            "status",
            "countryId",
        ];

        const invalidFields = Object.keys(rest).filter(
            (field) => !allowedFields.includes(field)
        );

        if (invalidFields.length > 0) {
            throw new ConstraintError(
                "Invalid fields in request",
                400,
                "INVALID_FIELDS",
                `The following fields cannot be updated: ${invalidFields.join(", ")}`
            );
        }

        const isExist = await visaRepo.exists({ id });

        if (!isExist) {
            throw new ConstraintError(
                "Visa not found",
                404,
                "RESOURCE_NOT_FOUND",
                `This Visa does not exist`
            );
        }

        if (countryId) {
            if (
                !countryId ||
                typeof countryId !== "string" ||
                countryId.trim() === "" ||
                !isValidUuid(countryId)
            ) {
                throw new ConstraintError(
                    "Invalid ID format",
                    400,
                    "VALIDATION_ERROR",
                    "Country ID must be a valid UUID"
                );
            }

            const countryExists = await countryRepo.countryExist({ id: countryId });

            if (!countryExists) {
                throw new ConstraintError(
                    "Country not found",
                    404,
                    "RESOURCE_NOT_FOUND",
                    `This Country could not be found`
                );
            }
        }

        const data = await visaRepo.updateVisa(id, {
            ...rest,
            ...(countryId && {
                country: {
                    connect: {
                        id: countryId,
                    },
                },
            }),
        });

        return data;
    },
};
