// package.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { PackageService } from "@core/app/services/package.service";
import { Request, Response } from "express";

export const PackageController = {
    createPackage: TryCatchBlock(async (req: Request, res: Response) => {
        const inputData = req.body;

        const result = await PackageService.createNewPackage(inputData);

        res.status(201).json({
            message: "Package created successfully",
            data: result,
        });
    }),

    addImages: TryCatchBlock(async (req: Request, res: Response) => {
        const inputData = {
            files: req.files as Express.Multer.File[],
            packageId: req.params.id,
        };

        const result = await PackageService.addImages(inputData);

        res.status(200).json({
            message: "Images added successfully",
            data: result,
        });
    }),
};
