// package.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { PackageService } from "@core/app/services/package.service";
import { Request, Response } from "express";

export const PackageController = {
    createPackage: TryCatchBlock(async (req: Request, res: Response) => {
        const inputData = req.body;

        const result = await PackageService.createNewPackage(inputData);

        res.status(201).json({
            message: "Package created successfully",
            data: result,
        });
    }),
};
