// passenger.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { PassengerService } from "@core/app/services/passenger.service";
import { Request, Response } from "express";

export const PassengerController = {
    createPassenger: TryCatchBlock(async (req: Request, res: Response) => {
        const data = await PassengerService.createPassenger({
            ...req.body,
            files: req.files as Express.Multer.File[],
        });

        res.status(201).json({
            message: "Passenger created successfully",
            data,
        });
    }),

    deletePassenger: TryCatchBlock(async (req: Request, res: Response) => {
        const { id } = req.params;

        await PassengerService.deletePassenger(id);

        res.status(200).json({
            message: "Passenger deleted successfully",
        });
    }),

    updatePassenger: TryCatchBlock(async (req: Request, res: Response) => {
        const { id } = req.params;
        const files = (req.files as Express.Multer.File[]) || [];

        const data = await PassengerService.updatePassenger({
            id,
            ...req.body,
            files,
        });

        res.status(200).json({
            message: "Passenger updated successfully",
            data,
        });
    }),
    // createPassenger: TryCatchBlock(async (req: Request, res: Response) => {}),
    // createPassenger: TryCatchBlock(async (req: Request, res: Response) => {}),
};
