// role.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { RoleService } from "@core/app/services/role.service";
import { Request, Response } from "express";

export const RoleController = {
    getAllRoles: TryCatchBlock(async (req: Request, res: Response) => {
        const roles = await RoleService.getAllRoles();
        res.status(200).json({
            message: "Roles fetched successfully",
            data: roles,
        });
    }),
};
