// visa.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { VisaService } from "@core/app/services/visa.service";
import { Request, Response } from "express";

export const VisaController = {
    createNewVisa: TryCatchBlock(async (req: Request, res: Response) => {
        const data = await VisaService.createNewVisa(req.body);
        res.status(201).json({
            message: "Visa created successfully",
            data,
        });
    }),
    getVisaById: TryCatchBlock(async (req: Request, res: Response) => {
        const data = await VisaService.getVisaById({
            id: req.params.id,
        });

        res.status(200).json({
            message: "Visa retrieved successfully",
            data,
        });
    }),
    deleteVisa: TryCatchBlock(async (req: Request, res: Response) => {
        await VisaService.deleteVisa({ id: req.params.id });
        res.status(200).json({
            message: "Visa deleted successfully",
        });
    }),
    updateVisa: TryCatchBlock(async (req: Request, res: Response) => {
        const { id } = req.params;

        const data = await VisaService.updateVisa({
            ...req.body,
            id,
        });

        res.status(200).json({
            message: "Visa updated successfully",
            data,
        });
    }),
    getAllVisas: TryCatchBlock(async (req: Request, res: Response) => {
        const { page = 1, pageSize = 10, countryId } = req.query;

        const data = await VisaService.getAllVisa({
            countryId: typeof countryId === "string" ? countryId : undefined,
            page: Number(page),
            pageSize: Number(pageSize),
        });

        res.status(200).json({
            message: "Visas retrieved successfully",
            data,
        });
    }),
};
