// visa-booking.ctrl.ts generated by generate.sh
import { TryCatchBlock } from "@/core/app/base/try-catch-block";
import { VisaBookingService } from "@core/app/services/visa-booking.service";
import { Request, Response } from "express";

export const VisaBookingController = {
    createVisaBooking: TryCatchBlock(async (req: Request, res: Response) => {
        const files = req.files;

        const data = await VisaBookingService.requestVisa({
            ...req.body,
            files,
        });

        res.status(201).json({
            message: "Visa booking request created successfully",
            data,
        });
    }),

    getAllVisaBookings: TryCatchBlock(async (req: Request, res: Response) => {
        const { page = 1, limit = 10 } = req.query;

        const data = await VisaBookingService.getAllVisaBookings({
            limit: Number(limit),
            page: Number(page),
        });

        res.status(200).json({
            message: "Visa bookings retrieved successfully",
            data,
        });
    }),

    getVisaBookingById: TryCatchBlock(async (req: Request, res: Response) => {
        const { id } = req.params;
        const data = await VisaBookingService.getVisaBookingById({
            id,
        });

        res.status(200).json({
            message: "Visa booking retrieved successfully",
            data,
        });
    }),

    updateVisaBooking: TryCatchBlock(async (req: Request, res: Response) => {}),

    deleteVisaBooking: TryCatchBlock(async (req: Request, res: Response) => {
        const { id } = req.params;
        await VisaBookingService.deleteVisaRequest({ id });
        res.status(204).json({
            message: "Visa booking deleted successfully",
        });
    }),
};
